name: Build And publish Docker Image on Github Packages

on:
  push:
    branches:
      - master
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to GitHub Container Registry
    uses: docker/login-action@v1
    with:
    registry: ghcr.io
    username: ${{ github.actor }}
    password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the Image and publish it as a github package
    run: |
          docker build . --tag ghcr.io/akash-bhavsar/fastapi-app:latest
          docker run ghcr.io/akash-bhavsar/fastapi-app:latest
          docker push ghcr.io/akash-bhavsar/fastapi-app:latest
